vscode:
  extensions:
    - sourcegraph.cody-ai

tasks:
  - name: Configurar persistência do Cody
    command: mkdir -p /workspace/.cody-history

gitConfig:
  alias.hist: log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short

ports:
  - port: 3000
    onOpen: open-preview

workspaceLocation: /workspace

additionalRepositories:
  - url: https://github.com/sourcegraph/cody
    checkoutLocation: .cody-source
