vscode:
  extensions:
    - sourcegraph.cody-ai
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - esbenp.prettier-vscode

    - google.geminicodeassist

tasks:
  - name: Configurar ambiente de desenvolvimento
    init: |
      cd influencehub
      npm install
    command: |
      cd influencehub
      npm run dev

  - name: Configurar persistência do Cody
    command: mkdir -p /workspace/.cody-history

gitConfig:
  alias.hist: log --pretty=format:'%h %ad | %s%d [%an]' --graph --date=short

ports:
  - port: 5173
    onOpen: open-preview
    visibility: public

additionalRepositories:
  - url: https://github.com/sourcegraph/cody
    checkoutLocation: .cody-source
